post http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "user1",
    "email": "skylantern19@gmail.com",
    "password": "user1"
}

###

post http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "skylantern19@gmail.com",
    "password": "user1"
}

###

get http://localhost:3000/api/auth/me

### 

post http://localhost:3000/api/notes
Content-Type: application/json

{
    "title": "test1",
    "content": "test1"
}